blog/urls.py
from django.urls import path

from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # Post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail, name='post_detail',),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    # path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    # path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    # Home page for reobrix.
    path('', views.index, name='index'),
    path('about-us/', views.about_us, name='about_us'),
    path('blog-single-post/', views.blog_single_post, name='blog_single_post'),
    path('blog/', views.blog, name='blog'),
    path('checkout/', views.checkout, name='checkout'),
    path('contacts/', views.contacts, name='contacts'),
    path('join_us/', views.join_us, name='join_us'),
    path('index/', views.index, name='index'),
    path('privacy/', views.privacy, name='privacy'),
    path('search-results/', views.search_results, name='search_results'),
    path('shop/', views.shop, name='shop'),
    path('single-product/', views.single_product, name='single_product'),
    path('subscribe/', views.subscribe, name='subscribe'),
    
]

reobrix/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from blog.sitemaps import PostSitemap, TagSitemap  # Import TagSitemap
from shop.sitemaps import ProductSitemap

from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts': PostSitemap,
    'tags': TagSitemap,
    'products': ProductSitemap,
}

urlpatterns = [
    path('my-admin/', admin.site.urls),
    # path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('core.urls', namespace='core')),
    
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField




class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name




class PublishedManager(models.Manager):
    def get_queryset(self):
        # Returns only the posts that have a status of 'PUBLISHED'
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        # Different statuses for a post
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)  # Title of the post
    slug = models.SlugField(max_length=250, unique_for_date='publish')  # Unique slug for the post
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_posts')
    author_image = models.ImageField(upload_to='authors/', blank=True, null=True)  # Optional author image
    # body = models.TextField()  # Content of the post
    body = RichTextUploadingField()  # Changed to CKEditor rich text uploading field
    publish = models.DateTimeField(default=timezone.now)  # Publish date of the post
    created = models.DateTimeField(auto_now_add=True)  # Auto set the field to now when the object is created
    updated = models.DateTimeField(auto_now=True)  # Auto set the field to now when the object is saved
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.PUBLISHED)  # Status of the post
    tags = TaggableManager(blank=True)  # Made tags optional
    categories = models.ManyToManyField(Category, related_name='posts', blank=True)  # Made categories optional
    featured_image = models.ImageField(upload_to='featured_images/', blank=True, null=True)


    objects = models.Manager()  # The default manager
    published = PublishedManager()  # Custom manager to handle published posts
    

    class Meta:
        ordering = ['-updated', '-publish']  # Order posts by publish date descending
        indexes = [models.Index(fields=['-publish'])]  # Index on the publish date for faster queries

    def __str__(self):
        return self.title  # String representation of the post

    def get_absolute_url(self):
        # Return the URL to the post detail page
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

    def get_embed_url(self):
        # Return the embed URL for a video post
        if self.post_type == self.PostType.VIDEO:
            from urllib.parse import urlparse, parse_qs
            url_data = urlparse(self.video_url)
            query = parse_qs(url_data.query)
            video_id = query["v"][0]
            return f"https://www.youtube.com/embed/{video_id}"
        return None

    def save(self, *args, **kwargs):
        # Ensure the slug is set before saving
        if not self.slug:
            from django.utils.text import slugify
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

blog/forms.py
from django import forms



class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea
    )



class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.contrib.postgres.search import SearchVector, TrigramSimilarity
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_POST
from taggit.models import Tag

from .forms import EmailPostForm, SearchForm
from .models import Post
from django.conf import settings


def post_list(request, tag_slug=None):
    # Retrieve all published posts
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        # Filter posts by the given tag
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    
    # Paginate the posts list, using the value from settings
    posts_per_page = getattr(settings, 'POSTS_PER_PAGE', 3)  # Default to 6 if setting is not defined
    paginator = Paginator(post_list, posts_per_page)
    page_number = request.GET.get('page', 1)

    tags = Tag.objects.all()  # Get all tags
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # If page_number is not an integer, get the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page_number is out of range, get last page of results
        posts = paginator.page(paginator.num_pages)
    
    return render(
        request,
        'blog/post/list.html',
        {
            'posts': posts,
            'tag': tag,
            'tags': tags,
        }
    )


def post_detail(request, year, month, day, post):
    # Retrieve the post based on the provided year, month, day, and slug
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(
        request,
        'blog/post/detail.html',
        {
            'post': post,
            'similar_posts': similar_posts,
        },
    )


def post_search(request):
    form = SearchForm()
    query = None
    results = Post.published.none()
    
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.annotate(search=SearchVector('title', 'body')).filter(search=query)
    
    # Paginate the posts list, using the value from settings
    posts_per_page = getattr(settings, 'POSTS_PER_PAGE', 3)  # Default to 6 if setting is not defined
    paginator = Paginator(results, posts_per_page)
    page_number = request.GET.get('page', 1)
    tags = Tag.objects.all()  # Get all tags

    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # If page_number is not an integer, get the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page_number is out of range, get last page of results
        posts = paginator.page(paginator.num_pages)

    return render(
        request,
        'blog/post/list.html',
        {
            'posts': posts,
            'query': query,
            'form': form,
            'tags': tags,
        }
    )


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} ({cd['email']}) recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n{cd['name']}'s comments: {cd['comments']}"
            send_mail(
                subject=subject,
                message=message,
                from_email=None,
                recipient_list=[cd['to']],
            )
            sent = True
    else:
        form = EmailPostForm()
    
    return render(
        request,
        'blog/post/share.html',
        {
            'post': post,
            'form': form,
            'sent': sent
        },
    )

blog/templates/blog/base_blog.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
<div class="blog-container">
  <aside class="sidebar">
    <!-- Sidebar content -->
  </aside>
  <div class="blog-main-content">
    <section>
      <!-- Modern Breadcrumbs-->
      <div class="parallax-container breadcrumb-modern bg-gray-darkest context-dark" data-parallax-img="{% static 'core/images/background-1-1920x651.svg' %}">
        <div class="parallax-content">
          <div class="bg-overlay-gray-darkest">
            <div class="container section-34 section-md-50 section-lg-110">
              <div class="text-extra-big font-accent d-none d-lg-block">
                <span class="big">Blogs</span>
              </div>
              <ul class="list-inline list-inline-dashed p offset-top-0">
                <li class="list-inline-item"><a class="small" href="{% url 'core:index' %}">Home</a></li>
                <!-- <li class="list-inline-item"><a class="small" href="shop.html">Shop</a></li> -->
                <li class="list-inline-item">Blogs&News</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% block blog_content %}
    {% endblock %}
  </div>
</div>
{% endblock %}

blog/templates/blog/sidebar.html
{% load static %}
<div class="col-lg-4 col-xl-3 offset-top-66 offset-lg-top-0">
    <!-- Section Blog Modern-->
    <aside>
      <div class="row">
        {% if author %}
        <div class="col-12">
          <!-- Member block type 3-->
          <div class="member-block-type-3 shadow-drop-lg">
            <div class="member-block-body">
              <img class="rounded-circle" src="{% if post.author_image %}{{ post.author_image.url }}{% else %}{% static "blog/img/small_logo.jpg" %}{% endif %}">
              <div class="offset-top-24">
                <div>
                  <h6 class="text-ubold text-uppercase">{{ author.get_full_name }}</h6>
                </div>
                <p class="small offset-top-10 text-primary">Handmader</p>
              </div>
            </div>
            <div class="btn-group btn-group-sm offset-top-34" role="group" aria-label="button">
              <a class="btn btn-default btn-icon btn-rect" href="#"><span class="icon novi-icon mdi mdi-facebook"></span></a>
              <a class="btn btn-default btn-icon btn-rect" href="#"><span class="icon novi-icon mdi mdi-twitter"></span></a>
            </div>
            <div class="member-block-footer"><a class="btn btn-sm btn-default btn-block btn-rect" href="#">All Posts</a></div>
          </div>
        </div>
        {% endif %}

        
        <div class="col-12 text-left {% if not author %} offset-top-66 {% else %} offset-top-41 {% endif %}">
          <!-- Search Form-->
          <h6 class="text-uppercase text-spacing-60">Search</h6>
          <div class="text-subline"></div>
          <div class="offset-top-34">
            <!-- RD Search Form-->
            <form class="form-search rd-search" action="{% url 'blog:post_search' %}" method="GET">
              <div class="form-group">
                <label class="form-label form-search-label form-label-sm" for="blog-sidebar-2-form-search-widget">Search</label>
                <input class="form-search-input input-sm form-control input-sm" id="blog-sidebar-2-form-search-widget" type="text" name="query" autocomplete="off">
              </div>
              <button class="form-search-submit" type="submit"><span class="mdi mdi-magnify novi-icon"></span></button>
            </form>
          </div>
        </div>
        


        <div class="col-12 offset-top-41 text-left">
          <!-- Tags-->
          <h6 class="text-uppercase text-spacing-60">Tags</h6>
          <div class="text-subline"></div>
          <div class="offset-top-34 context-light">


            <div class="group-xs tag-list">
                {% for tag in tags %}
                  <a class="btn-ellipse text-ubold btn btn-xs btn-default" href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                {% endfor %}
              </div>
              
          </div>
        </div>
      </div>
    </aside>
  </div>
  