blog/urls.py
from django.urls import path

from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # Post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail, name='post_detail',),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    # path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    # path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    # Home page for reobrix.
    path('', views.index, name='index'),
    path('about-us/', views.about_us, name='about_us'),
    path('blog-single-post/', views.blog_single_post, name='blog_single_post'),
    path('blog/', views.blog, name='blog'),
    path('checkout/', views.checkout, name='checkout'),
    path('contacts/', views.contacts, name='contacts'),
    path('join_us/', views.join_us, name='join_us'),
    path('index/', views.index, name='index'),
    path('privacy/', views.privacy, name='privacy'),
    path('search-results/', views.search_results, name='search_results'),
    path('shop/', views.shop, name='shop'),
    path('single-product/', views.single_product, name='single_product'),
    path('subscribe/', views.subscribe, name='subscribe'),
    
]

reobrix/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from blog.sitemaps import PostSitemap, TagSitemap  # Import TagSitemap
from shop.sitemaps import ProductSitemap

from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts': PostSitemap,
    'tags': TagSitemap,
    'products': ProductSitemap,
}

urlpatterns = [
    path('my-admin/', admin.site.urls),
    # path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('core.urls', namespace='core')),
    
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('json/', views.product_list_json, name='product_list_json'),
    path('json/category/<slug:category_slug>/', views.product_list_json, name='product_list_json_by_category'),
    path('json/collection/<slug:collection_slug>/', views.product_list_json, name='product_list_json_by_collection'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('collection/<slug:collection_slug>/', views.product_list, name='product_list_by_collection'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField




class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name




class PublishedManager(models.Manager):
    def get_queryset(self):
        # Returns only the posts that have a status of 'PUBLISHED'
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        # Different statuses for a post
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)  # Title of the post
    slug = models.SlugField(max_length=250, unique_for_date='publish')  # Unique slug for the post
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_posts')
    author_image = models.ImageField(upload_to='authors/', blank=True, null=True)  # Optional author image
    # body = models.TextField()  # Content of the post
    body = RichTextUploadingField()  # Changed to CKEditor rich text uploading field
    publish = models.DateTimeField(default=timezone.now)  # Publish date of the post
    created = models.DateTimeField(auto_now_add=True)  # Auto set the field to now when the object is created
    updated = models.DateTimeField(auto_now=True)  # Auto set the field to now when the object is saved
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.PUBLISHED)  # Status of the post
    tags = TaggableManager(blank=True)  # Made tags optional
    categories = models.ManyToManyField(Category, related_name='posts', blank=True)  # Made categories optional
    featured_image = models.ImageField(upload_to='featured_images/', blank=True, null=True)


    objects = models.Manager()  # The default manager
    published = PublishedManager()  # Custom manager to handle published posts
    

    class Meta:
        ordering = ['-updated', '-publish']  # Order posts by publish date descending
        indexes = [models.Index(fields=['-publish'])]  # Index on the publish date for faster queries

    def __str__(self):
        return self.title  # String representation of the post

    def get_absolute_url(self):
        # Return the URL to the post detail page
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

    def get_embed_url(self):
        # Return the embed URL for a video post
        if self.post_type == self.PostType.VIDEO:
            from urllib.parse import urlparse, parse_qs
            url_data = urlparse(self.video_url)
            query = parse_qs(url_data.query)
            video_id = query["v"][0]
            return f"https://www.youtube.com/embed/{video_id}"
        return None

    def save(self, *args, **kwargs):
        # Ensure the slug is set before saving
        if not self.slug:
            from django.utils.text import slugify
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

blog/forms.py
from django import forms



class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea
    )



class SearchForm(forms.Form):
    query = forms.CharField()

core/forms.py
# forms.py
from django import forms
from .models import Subscriber
from django_recaptcha.fields import ReCaptchaField

class SubscriberForm(forms.ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Subscriber
        fields = ['email', 'captcha']

blog/views.py
from django.contrib.postgres.search import SearchVector, TrigramSimilarity
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_POST
from taggit.models import Tag

from .forms import EmailPostForm, SearchForm
from .models import Post
from django.conf import settings


def post_list(request, tag_slug=None):
    # Retrieve all published posts
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        # Filter posts by the given tag
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    
    # Paginate the posts list, using the value from settings
    posts_per_page = getattr(settings, 'POSTS_PER_PAGE', 3)  # Default to 6 if setting is not defined
    paginator = Paginator(post_list, posts_per_page)
    page_number = request.GET.get('page', 1)

    tags = Tag.objects.all()  # Get all tags
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # If page_number is not an integer, get the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page_number is out of range, get last page of results
        posts = paginator.page(paginator.num_pages)
    
    return render(
        request,
        'blog/post/list.html',
        {
            'posts': posts,
            'tag': tag,
            'tags': tags,
        }
    )


def post_detail(request, year, month, day, post):
    # Retrieve the post based on the provided year, month, day, and slug
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(
        request,
        'blog/post/detail.html',
        {
            'post': post,
            'similar_posts': similar_posts,
        },
    )


def post_search(request):
    form = SearchForm()
    query = None
    results = Post.published.none()
    
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.annotate(search=SearchVector('title', 'body')).filter(search=query)
    
    # Paginate the posts list, using the value from settings
    posts_per_page = getattr(settings, 'POSTS_PER_PAGE', 3)  # Default to 6 if setting is not defined
    paginator = Paginator(results, posts_per_page)
    page_number = request.GET.get('page', 1)
    tags = Tag.objects.all()  # Get all tags

    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # If page_number is not an integer, get the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page_number is out of range, get last page of results
        posts = paginator.page(paginator.num_pages)

    return render(
        request,
        'blog/post/list.html',
        {
            'posts': posts,
            'query': query,
            'form': form,
            'tags': tags,
        }
    )


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} ({cd['email']}) recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n{cd['name']}'s comments: {cd['comments']}"
            send_mail(
                subject=subject,
                message=message,
                from_email=None,
                recipient_list=[cd['to']],
            )
            sent = True
    else:
        form = EmailPostForm()
    
    return render(
        request,
        'blog/post/share.html',
        {
            'post': post,
            'form': form,
            'sent': sent
        },
    )

core/views.py
from django.http import HttpResponse
from .models import Slide, HomepageContent
from django.http import Http404

from django.shortcuts import render, get_object_or_404, redirect
from shop.models import Product, Collection
from blog.models import Post


from taggit.models import Tag
from django import forms
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.postgres.search import SearchVector
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank



from .tasks import test, fucking_print



from django.contrib import messages
from .forms import SubscriberForm



def index(request):
    try:
        new_arrivals_collection = get_object_or_404(Collection, slug="new-arrivals")
    except Http404:
        new_arrivals_collection = None

    try:
        popular_collection = get_object_or_404(Collection, slug="popular")
    except Http404:
        popular_collection = None

    if new_arrivals_collection:
        new_arrivals = Product.objects.filter(collections=new_arrivals_collection, available=True).order_by('-created')[:]
    else:
        new_arrivals = []

    if popular_collection:
        popular_products = Product.objects.filter(collections=popular_collection, available=True).order_by('-created')[:4]
    else:
        popular_products = []

    slides = Slide.objects.all()  # Assuming you have a Slide model for slides
    slide_count = slides.count()


    latest_featured_image_posts = Post.objects.filter(tags__name__in=["homepage_post"]).order_by('-created')

    homepage_content = HomepageContent.objects.first()  # Get the first (or only) HomepageContent object
    
    # Ensure latest_classic_image_posts has exactly 4 items
    # if latest_classic_image_posts.count() < 4:
    #     # Repeat the last item to fill up to 4 items
    #     if latest_classic_image_posts.exists():
    #         last_post = latest_classic_image_posts.last()
    #         remaining_posts_needed = 4 - latest_classic_image_posts.count()
    #         for _ in range(remaining_posts_needed):
    #             latest_classic_image_posts = latest_classic_image_posts | Post.objects.filter(pk=last_post.pk)
    #     else:
    #         latest_classic_image_posts = Post.objects.none()

    latest_featured_image_posts = latest_featured_image_posts[:4]  # Limit to 4 items

    upcoming_products_blog_list = Post.objects.filter(tags__name__in=["upcoming_products"])
    


    context = {
        'new_arrivals': new_arrivals,
        'popular_products': popular_products,
        'slides': slides,
        'latest_featured_image_posts': latest_featured_image_posts,
        'upcoming_products_blog_list': upcoming_products_blog_list,
        'content': homepage_content,       
    }
    return render(request, 'core/index.html', context)





def about_us(request):
    # f("fuckfuckfuck")
    # launch asynchronous task
    # print(f"fucking test111")
    # try:
    #     test.delay("tesing this celery rabbitmq...")
    # except:
    #     print("Celery...failed.")
    print(f"fucking test2")
    return render(request, 'core/about-us.html')


def blog_single_post(request):
    return render(request, 'core/blog-single-post.html')


def blog(request):
    return render(request, 'core/blog.html')


def checkout(request):
    return render(request, 'core/checkout.html')


def contacts(request):
    return render(request, 'core/contacts.html')



def join_us(request):
    return render(request, 'core/join-us.html')


# def index(request):
#     return render(request, 'core/index.html')


def privacy(request):
    return render(request, 'core/privacy.html')


class SearchForm(forms.Form):
    query = forms.CharField()


def search(request, queryset, search_fields):
    form = SearchForm()
    query = None
    results = queryset.none()

    if 'query' in request.GET:
        form = SearchForm(request.GET)

        if form.is_valid():
            query = form.cleaned_data['query']
            print(query, type(query))
            search_vector = SearchVector(*search_fields)
            print(*search_fields)
            results = queryset.annotate(search=search_vector).filter(search=query)
    
    paginator = Paginator(results, 3)  # Paginate with 3 items per page
    page_number = request.GET.get('page', 1)

    try:
        items = paginator.page(page_number)
    except PageNotAnInteger:
        # If page_number is not an integer, get the first page
        items = paginator.page(1)
    except EmptyPage:
        # If page_number is out of range, get the last page of results
        items = paginator.page(paginator.num_pages)

    return render(
        request,
        'shop/product/list.html',
        {
            'products': items,
            'query': query,
            'form': form,
        }


        # {
        #     'category': category,
        #     'collection': collection,
        #     'categories': categories,
        #     'collections': collections,
        #     'products': products,
        # }
    )




def search_results(request):
    queryset = Product.objects.filter(available=True)
    print(f'{len(queryset)}')
    search_fields = ['name', 'description', 'short_description']
    return search(request, queryset, search_fields)
    # return render(request, 'core/search-results.html')


def shop(request):
    return render(request, 'core/shop.html')


def single_product(request):
    return render(request, 'core/single-product.html')




def subscribe(request):
    if request.method == 'POST':
        form = SubscriberForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Thank you for subscribing!')
            return redirect('subscribe')
        else:
            messages.error(request, 'There was an error with your submission.')
    else:
        form = SubscriberForm()

    return render(request, 'subscribe.html', {'form': form})

core/templates/core/about-us.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}


<section>
  <!-- Modern Breadcrumbs-->
  <div class="parallax-container breadcrumb-modern bg-gray-darkest context-dark" data-parallax-img="{% static 'core/images/background-1-1920x651.jpg' %}">
    <div class="parallax-content">
      <div class="bg-overlay-gray-darkest">
        <div class="container section-34 section-md-50 section-lg-110">
          <div class="text-extra-big font-accent d-none d-lg-block"><span class="big">About Us</span></div>
          <ul class="list-inline list-inline-dashed p offset-top-0">
            <li class="list-inline-item"><a class="small" href="index.html">Home</a></li>
            <li class="list-inline-item">About
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Who We Are-->
<section class="section-98 section-md-110 novi-background" data-preset='{"title":"Content block 3","category":"content","reload":true,"id":"content-block-3"}'>
  <div class="container">
    <h1 class="text-between">Who We Are</h1>
    <div class="row justify-content-sm-center">
      <div class="col-md-10 offset-top-50 offset-lg-top-0 col-lg-10 col-xl-8 text-md-left inset-lg-right-30">
        <p>Reobrix is a leading building block manufacturer based in China, specializing in high-quality, LEGO-like bricks that inspire creativity and provide a unique building experience for enthusiasts of all ages. With a diverse range of product collections, including Block Gun Collection, Submarine Series, Military Aircraft Collection, and more, we cater to a wide array of interests and hobbies. Our commitment to quality and innovation has earned us a loyal customer base and long-term partnerships with well-known brands.</p>
        <p>At Reobrix, we are dedicated to the construction and development of brand culture, creativity, and high standards of quality. Our products are crafted with precision and care, ensuring an engaging and rewarding assembly experience. Our latest offerings include highly detailed models like the Reobrix Cathedral of Notre Dame and UCS-Style Star Shuttle, which not only provide an immersive building experience but also serve as magnificent display pieces. We are constantly striving to bring new and exciting products to our customers, and we are excited to continue growing and evolving as a company.</p>
      </div>

    </div>
  </div>
</section>
<!-- HDW-->
<section class="context-dark" data-preset='{"title":"Content block 4","category":"content, parallax","reload":true,"id":"content-block-4"}'>
  <div class="parallax-container" data-parallax-img="{% static 'core/images/background-2-1920x1184.jpg' %}">
    <div class="parallax-content">
      <div class="section-98 section-md-124 bg-overlay-gray-darkest">
        <div class="container">
          <div class="row justify-content-center grid-group-md">
            <div class="col-md-8 col-lg-4">
              <!-- Icon Box Type 4--><span class="icon novi-icon icon-circle icon-bordered icon-carrot-filled icon-outlined mdi mdi-monitor"></span>
              <div>
                <h4 class="text-uppercase offset-top-30 font-weight-bold">VARIETY</h4>
                <p>
                  Diverse range, caters to various interests.
                  
                </p>
              </div>
            </div>
            <div class="col-md-8 col-lg-4">
              <!-- Icon Box Type 4--><span class="icon novi-icon icon-circle icon-bordered icon-carrot-filled icon-outlined mdi mdi-rocket"></span>
              <div>
                <h4 class="text-uppercase offset-top-30 font-weight-bold">DESIGN</h4>
                <p>
                  Inspired, intricate, and captivating.
                  
                </p>
              </div>
            </div>
            <div class="col-md-8 col-lg-4">
              <!-- Icon Box Type 4--><span class="icon novi-icon icon-circle icon-bordered icon-carrot-filled icon-outlined mdi mdi-xml"></span>
              <div>
                <h4 class="text-uppercase offset-top-30 font-weight-bold">QUALITY</h4>
                <p>
                  Precision-crafted, durable, and high-quality.
                  
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- What Clients Say?-->
<section class="section-98 section-md-110 bg-lighter novi-background" data-preset='{"title":"Testimonials","category":"testimonials, carousel","reload":true,"id":"testimonials"}'>
  <div class="container">
    <h1 class="text-between">What Clients Say?</h1>
    <div class="row justify-content-sm-center offset-top-66">
      <div class="col-sm-10 col-md-8 col-xl-12">
        <div class="owl-carousel owl-carousel-classic owl-carousel-class-light owl-carousel-testimonials-3 veil-owl-nav" data-items="1" data-stage-padding="10" data-margin="25" data-xl-margin="25" data-xl-items="3" data-nav="false" data-dots="true">
          <div>
            <!-- Boxed Testimonials v2-->
            <blockquote class="quote quote-classic quote-classic-boxed-2">
              <div class="quote-meta"><img class="rounded-circle quote-img" width="80" height="80" src="{% static 'core/images/user-katherine-ferguson-80x80.jpg' %}" alt=""></div>
              <div class="quote-body">
                <p>
                  <q>Reobrix models are amazing – detailed, high-quality, and a joy to build. The Cathedral of Notre Dame set was stunning. Highly recommend!</q>
                </p>
                <h6 class="quote-author text-uppercase">
                  <cite class="text-normal">Katherine Ferguson</cite>
                </h6>
                <p class="quote-desc text-uppercase text-warning">United States</p>
              </div>
            </blockquote>
          </div>
          <div>
            <!-- Boxed Testimonials v2-->
            <blockquote class="quote quote-classic quote-classic-boxed-2">
              <div class="quote-meta"><img class="rounded-circle quote-img" width="80" height="80" src="{% static 'core/images/user-alisa-milano-80x80.jpg' %}" alt=""></div>
              <div class="quote-body">
                <p>
                  <q>Love Reobrix's Military Aircraft Collection. The detail and quality are top-notch. I'm proud to display it in my home and show it off to my friends and family.</q>
                </p>
                <h6 class="quote-author text-uppercase">
                  <cite class="text-normal">Alisa Milano</cite>
                </h6>
                <p class="quote-desc text-uppercase text-warning">United States</p>
              </div>
            </blockquote>
          </div>
          <div>
            <!-- Boxed Testimonials v2-->
            <blockquote class="quote quote-classic quote-classic-boxed-2">
              <div class="quote-meta"><img class="rounded-circle quote-img" width="80" height="80" src="{% static 'core/images/user-betty-hunt-80x80.jpg' %}" alt=""></div>
              <div class="quote-body">
                <p>
                  <q>Reobrix has a wide range of products and excellent customer service. The building blocks are top-quality, and I'm always impressed with their designs.</q>
                </p>
                <h6 class="quote-author text-uppercase">
                  <cite class="text-normal">Betty Hunt</cite>
                </h6>
                <p class="quote-desc text-uppercase text-warning">Canada</p>
              </div>
            </blockquote>
          </div>
          <div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

core/templates/core/breadcrumbs.html
<!-- templates/core/breadcrumbs.html -->
{% load static %}
<section>
  <!-- Modern Breadcrumbs-->
  <div class="parallax-container breadcrumb-modern bg-gray-darkest context-dark" data-parallax-img="{% static 'core/images/background-1-1920x651.svg' %}">
    <div class="parallax-content">
      <div class="bg-overlay-gray-darkest">
        <div class="container section-34 section-md-50 section-lg-110">
          <div class="text-extra-big font-accent d-none d-lg-block">
            <span class="big">
              {% if breadcrumbs %}
                {% with last_breadcrumb=breadcrumbs|last %}
                  {{ last_breadcrumb.name }}
                {% endwith %}
              {% endif %}
            </span>
          </div>
          <ul class="list-inline list-inline-dashed p offset-top-0">
            <li class="list-inline-item"><a class="small" href="{% url 'core:index' %}">Home</a></li>
            {% for crumb in breadcrumbs %}
              {% if not forloop.last %}
                <li class="list-inline-item"><a class="small" href="{{ crumb.url }}">{{ crumb.name }}</a></li>
              {% else %}
                <li class="list-inline-item">{{ crumb.name }}</li>
              {% endif %}
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

core/templates/core/join-us.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}


<section>
  <!-- Modern Breadcrumbs-->
  <div class="parallax-container breadcrumb-modern bg-gray-darkest context-dark" data-parallax-img="{% static 'core/images/background-1-1920x651.jpg' %}">
    <div class="parallax-content">
      <div class="bg-overlay-gray-darkest">
        <div class="container section-34 section-md-50 section-lg-110">
          <div class="text-extra-big font-accent d-none d-lg-block"><span class="big">Join Us</span></div>
          <ul class="list-inline list-inline-dashed p offset-top-0">
            <li class="list-inline-item"><a class="small" href="index.html">Home</a></li>
            <li class="list-inline-item">About
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Who We Are-->
<section class="section-98 section-md-110 novi-background" data-preset='{"title":"Content block 3","category":"content","reload":true,"id":"content-block-3"}'>
  <div class="container">
    <h1 class="text-between">Interested in wholesale opportunities?</h1>
    <div class="row justify-content-sm-center">
      <div class="col-md-10 offset-top-50 offset-lg-top-0 col-lg-10 col-xl-8 text-md-left inset-lg-right-30">
        <p>
          Explore the world of Reobrix Wholesale, where innovation and creativity come to life through our unique building block sets. Ideal for retailers looking to inspire and captivate, our products promise to spark imagination in every builder.
          <br><br>
          Please get in touch at <a href="mailto:info@reobrix.com" style="color: #0066cc; text-decoration: none; font-weight: bold; border-bottom: 2px solid #0066cc; padding-bottom: 2px;">info@reobrix.com</a>.
          <br><br>
          Together, let's create extraordinary experiences.
        </p>
        

    </div>
  </div>
</section>


{% endblock %}

core/templates/core/search-results.html
{% extends "core/base.html" %}
{% load static %}

{% load blog_tags %}

{% block content %}


      <section>
        <!-- Modern Breadcrumbs-->
        <div class="parallax-container breadcrumb-modern bg-gray-darkest context-dark" data-parallax-img="{% static 'core/images/background-1-1920x651.jpg' %}">
          <div class="parallax-content">
            <div class="bg-overlay-gray-darkest">
              <div class="container section-34 section-md-50 section-lg-110">
                <div class="text-extra-big font-accent d-none d-lg-block"><span class="big">Search Results</span></div>
                <ul class="list-inline list-inline-dashed p offset-top-0">
                  <li class="list-inline-item"><a class="small" href="index.html">Home</a></li>
                  <li class="list-inline-item">Search Results XXX
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>




      <section class="section-98 section-md-124 novi-background" data-preset='{"title":"Search","category":"search","reload":true,"id":"search"}'>
        <div class="container">
          {% if query %}
          <h1>Posts containing "{{ query }}"</h1>
          <h3>
            {% with results.count as total_results %}
              Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
          </h3>
          {% for post in items %}
            <h4>
              <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
              </a>
            </h4>
            {{ post.body|markdown|truncatewords_html:12 }}
          {% empty %}
            <p>There are no results for your query.</p>
          {% endfor %}
          <p><a href="{% url "blog:post_search" %}">Search again</a></p>
        {% else %}
          <h1>Search for posts</h1>
          <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
          </form>
        {% endif %}


          <!-- RD Search Form-->
          <form class="form-search rd-search" action="{% url 'core:search_results' %}" method="GET">
            <div class="form-group">
              <label class="form-label form-search-label form-label-sm" for="search-results">Search</label>
              <input class="form-search-input input-sm form-control input-sm" id="search-results" type="text" name="query" autocomplete="off">
            </div>
            <button class="form-search-submit" type="submit"><span class="mdi mdi-magnify novi-icon"></span></button>
          </form>
          <div class="rd-search-results offset-top-66"></div>
        </div>
      </section>

{% endblock %}